<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNvlumpx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNvlumpx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNvlumpx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNvlumpx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNvlumpx\appDevDebugProjectContainer([
    'container.build_hash' => 'Nvlumpx',
    'container.build_id' => 'eed5c7eb',
    'container.build_time' => 1553369744,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNvlumpx');
