<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGwn1t4b\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGwn1t4b/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGwn1t4b.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGwn1t4b\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGwn1t4b\appDevDebugProjectContainer([
    'container.build_hash' => 'Gwn1t4b',
    'container.build_id' => '8523df31',
    'container.build_time' => 1553206170,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGwn1t4b');
