<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5y3pxrf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5y3pxrf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5y3pxrf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5y3pxrf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container5y3pxrf\appDevDebugProjectContainer([
    'container.build_hash' => '5y3pxrf',
    'container.build_id' => 'c94a8aec',
    'container.build_time' => 1553437891,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5y3pxrf');
