<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFaeumdk\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFaeumdk/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFaeumdk.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFaeumdk\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFaeumdk\appProdProjectContainer([
    'container.build_hash' => 'Faeumdk',
    'container.build_id' => '8340b420',
    'container.build_time' => 1552150098,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFaeumdk');
