<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX1atulg\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX1atulg/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX1atulg.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX1atulg\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerX1atulg\appDevDebugProjectContainer([
    'container.build_hash' => 'X1atulg',
    'container.build_id' => '3616ba99',
    'container.build_time' => 1553206491,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX1atulg');
