# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_DEV:         ROLE_USER
        ROLE_CHIEF:       [ ROLE_USER, ROLE_CHIEF]
        ROLE_ADMIN:       [ ROLE_ADMIN, ROLE_USER, ROLE_CHIEF]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:     true
            anonymous:  true

    access_control:
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/task/, role: ROLE_DEV }
        - { path: ^/project/, role: ROLE_CHIEF }
        - { path: ^/(login$|resetting|register), role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY}


