<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQvgp1cr\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQvgp1cr/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQvgp1cr.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQvgp1cr\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQvgp1cr\appDevDebugProjectContainer([
    'container.build_hash' => 'Qvgp1cr',
    'container.build_id' => 'c050cce2',
    'container.build_time' => 1552742810,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQvgp1cr');
