<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIhovemm\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIhovemm/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIhovemm.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIhovemm\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIhovemm\appDevDebugProjectContainer([
    'container.build_hash' => 'Ihovemm',
    'container.build_id' => 'ac42fd77',
    'container.build_time' => 1552393935,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIhovemm');
